# Generated by Django 5.0.2 on 2024-02-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
