# Generated by Django 5.0.2 on 2024-02-11 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_alter_job_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
